name: 🕒 Daily Auto Commit

on:
  schedule:
    - cron: "16 8 * * *"  # Every day at 7 AM UTC (adjust as needed)
  workflow_dispatch:      # Allows manual runs too

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make changes to file
        run: |
          echo "Auto-update: $(date)" >> log.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🤖 Daily auto-commit: $(date)"
          git push
